# Generated by Django 5.2.4 on 2025-08-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Job', models.CharField(max_length=100)),
                ('Safety', models.CharField(max_length=100)),
                ('Supervisor', models.CharField(max_length=100)),
                ('JSA', models.CharField(max_length=100)),
                ('Risk', models.CharField(max_length=100)),
                ('Loading', models.CharField(max_length=100)),
                ('Emergency', models.CharField(max_length=100)),
                ('Incident', models.CharField(max_length=100)),
                ('LOTO', models.CharField(max_length=100)),
                ('Safety1', models.CharField(max_length=100)),
                ('Hazard', models.CharField(max_length=100)),
                ('Fire', models.CharField(max_length=100)),
                ('Electrical', models.CharField(max_length=100)),
                ('HotWork', models.CharField(max_length=100)),
                ('CHMP', models.CharField(max_length=100)),
                ('Ground', models.CharField(max_length=100)),
                ('Confined', models.CharField(max_length=100)),
                ('Fall', models.CharField(max_length=100)),
                ('Defensive', models.CharField(max_length=100)),
                ('Scaffold', models.CharField(max_length=100)),
                ('Flagman', models.CharField(max_length=100)),
                ('Certificate', models.CharField(max_length=100)),
                ('Crane', models.CharField(max_length=100)),
                ('Rigger', models.CharField(max_length=100)),
                ('Hoisting', models.CharField(max_length=100)),
                ('Welder', models.CharField(max_length=100)),
                ('Diesel', models.CharField(max_length=100)),
                ('PPE', models.CharField(max_length=100)),
                ('Heat', models.CharField(max_length=100)),
                ('Load', models.CharField(max_length=100)),
                ('GoldenRules', models.CharField(max_length=100)),
                ('HAVS', models.CharField(max_length=100)),
                ('Dropped', models.CharField(max_length=100)),
                ('LOF', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='familiya',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ism',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='malumot',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telefon',
        ),
        migrations.AddField(
            model_name='contact',
            name='CHMP',
            field=models.CharField(default='-', max_length=100, verbose_name='CHWP Receiver & Issuer\nПолучатель и Выдаватель CHWP'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Certificate',
            field=models.CharField(default='-', max_length=100, verbose_name='Scaffolding-related Certificate\nСертификат по строительным лесам'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Confined',
            field=models.CharField(default='-', max_length=100, verbose_name='Confined Space\nОграниченные пространства. Замккнутий пронс'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Crane',
            field=models.CharField(default='-', max_length=100, verbose_name='Crane Operator Qualification Certificate\nКвалификационное удостоверение машиниста крана'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Defensive',
            field=models.CharField(default='-', max_length=100, verbose_name='Defensive driving\nБезопасный вождение'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Diesel',
            field=models.CharField(default='-', max_length=100, verbose_name='Training for diesel mechanics\nОбучение для дизелистов'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Dropped',
            field=models.CharField(default='-', max_length=100, verbose_name='Dropped Objects Campaign\nКампания Упавшие предметы'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Electrical',
            field=models.CharField(default='-', max_length=100, verbose_name='Electrical Safety\nЭлектробезопасность'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Emergency',
            field=models.CharField(default='-', max_length=100, verbose_name='Emergency Response\nЭкстренное реагирование'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Fall',
            field=models.CharField(default='-', max_length=100, verbose_name='Fall Protection & Dropped Objects\nЗащита от падения и падающих предметов'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Fire',
            field=models.CharField(default='-', max_length=100, verbose_name='Fire Prevention\nПредотвращение пожаров'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Flagman',
            field=models.CharField(default='-', max_length=100, verbose_name='Flagman\nСигнальщик'),
        ),
        migrations.AddField(
            model_name='contact',
            name='GoldenRules',
            field=models.CharField(default='-', max_length=100, verbose_name='10 IIF/BSG Golden Rules\n10 Золотых правил охраны труда и техники безопасности'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Ground',
            field=models.CharField(default='-', max_length=100, verbose_name='Ground Disturbance: Pilling. Excavation & Trenching\nРазрушение грунта: Пиллинг. раскопки и рытье траншей ер ишлари'),
        ),
        migrations.AddField(
            model_name='contact',
            name='HAVS',
            field=models.CharField(default='-', max_length=100, verbose_name='Hand Safety Campaign HAVS\nКампания по безопасности рук'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Hazard',
            field=models.CharField(default='-', max_length=100, verbose_name='Hazard Communications/Use Hazardous Material \nОпасные связи/Использование опасных материалов'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Heat',
            field=models.CharField(default='-', max_length=100, verbose_name='Heat Stress Campaign\nКампания потив теплового стресса'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Hoisting',
            field=models.CharField(default='-', max_length=100, verbose_name='Hoisting and Lifting supervisor qualification/certificate\nКвалификация/сертификат супервайзера по грузоподъемным машинам и подъемникам'),
        ),
        migrations.AddField(
            model_name='contact',
            name='HotWork',
            field=models.CharField(default='-', max_length=100, verbose_name='Hotwork\nОгневые работы'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Incident',
            field=models.CharField(default='-', max_length=100, verbose_name='Incident Management\nУправление инцидентами'),
        ),
        migrations.AddField(
            model_name='contact',
            name='JSA',
            field=models.CharField(default='-', max_length=100, verbose_name='Awareness of Job Safety Analysis (JSA)\nОсведомленность о  Анализ безопасности работы (АБР)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Job',
            field=models.CharField(default='-', max_length=100, verbose_name='Job Title\nДолжность'),
        ),
        migrations.AddField(
            model_name='contact',
            name='LOF',
            field=models.CharField(default='-', max_length=100, verbose_name='Line of Fire Campaign\nКампания Линия огня'),
        ),
        migrations.AddField(
            model_name='contact',
            name='LOTO',
            field=models.CharField(default='-', max_length=100, verbose_name='LOTO'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Load',
            field=models.CharField(default='-', max_length=100, verbose_name='Load Handling Campaign\nКампания по погрузке-разгрузке'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Loading',
            field=models.CharField(default='-', max_length=100, verbose_name='Loading & \nПогрузка и разгрузка'),
        ),
        migrations.AddField(
            model_name='contact',
            name='PPE',
            field=models.CharField(default='-', max_length=100, verbose_name='Transportation of hazardous substances and distribution of fuel and lubricants\nПеревозка опасных веществ и раздача ГСМ'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Rigger',
            field=models.CharField(default='-', max_length=100, verbose_name='Rigger qualification certificate \nКвалификационное удостоверение стропальщика'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Risk',
            field=models.CharField(default='-', max_length=100, verbose_name='Risk Management (HAZID. RAMS. JSA)(HAZID. RAMS. JSA)\nУправление рисками (HAZID. RAMS. JSA) (HAZID. RAMS. JSA)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Safety',
            field=models.CharField(default='-', max_length=100, verbose_name='Safety Induction\nВводный инструктаж'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Safety1',
            field=models.CharField(default='-', max_length=100, verbose_name='Safety Induction\nВводный инструктаж'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Scaffold',
            field=models.CharField(default='-', max_length=100, verbose_name='Scaffold User\nСтроительные леса - Пользователь'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Supervisor',
            field=models.CharField(default='-', max_length=100, verbose_name='Supervisor Leadership Training / BSP /\nТренинг лидерства для руководителей / BSP'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Welder',
            field=models.CharField(default='-', max_length=100, verbose_name='Welder qualification\nКвалификация сварщика'),
        ),
        migrations.AddField(
            model_name='contact',
            name='med',
            field=models.CharField(default='-', max_length=100, verbose_name='Medical Certificate\nМедицинская справка'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='-', max_length=100, verbose_name='First Name\nИмя'),
        ),
    ]
