# Generated by Django 5.2.4 on 2025-08-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_training_remove_contact_familiya_remove_contact_ism_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(default='-', max_length=100, verbose_name='Number\nНомер'),
        ),
        migrations.AddField(
            model_name='training',
            name='number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
