# Generated by Django 5.2.4 on 2025-08-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_number_training_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(default=' ', max_length=100, verbose_name='Number\nНомер'),
        ),
    ]
