# Generated by Django 5.2.4 on 2025-08-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['auto_number'], 'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
        migrations.RemoveField(
            model_name='training',
            name='id',
        ),
        migrations.RemoveField(
            model_name='training',
            name='number',
        ),
        migrations.AddField(
            model_name='contact',
            name='auto_number',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True, verbose_name='№'),
        ),
        migrations.AddField(
            model_name='training',
            name='auto_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
