# Generated by Django 5.2.4 on 2025-08-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contact_chmp_alter_contact_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='auto_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='№'),
        ),
    ]
