# Generated by Django 5.2.4 on 2025-08-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contact_auto_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='auto_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='№'),
        ),
    ]
