# Generated by Django 5.2.4 on 2025-09-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_training_med_alter_contact_chmp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={},
        ),
        migrations.AddField(
            model_name='contact',
            name='Auto',
            field=models.CharField(default='0', max_length=100, verbose_name='Auto hydraulic lift / Авто гидро подемник'),
        ),
        migrations.AddField(
            model_name='contact',
            name='DrLicense',
            field=models.CharField(default='0', max_length=100, verbose_name="Driver's License / Водителская Удостореваная"),
        ),
        migrations.AddField(
            model_name='contact',
            name='Qualific',
            field=models.CharField(default='0', max_length=100, verbose_name='Abduction qualifications / Повищения кволификатсия'),
        ),
        migrations.AddField(
            model_name='training',
            name='Auto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='training',
            name='DrLicense',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='training',
            name='Qualific',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Fall',
            field=models.CharField(default='0', max_length=100, verbose_name='Fall Protection & Dropped Objects\nРабота на высоте'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Job',
            field=models.CharField(default='0', max_length=100, verbose_name='Job/Должность'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Risk',
            field=models.CharField(default='0', max_length=100, verbose_name='Risk Management (HAZID. RAMS. JSA)\nУправление рисками'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Safety',
            field=models.CharField(default='0', max_length=100, verbose_name='Safety Induction\nВводный инструктаж AR'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Safety1',
            field=models.CharField(default='0', max_length=100, verbose_name='Вводный инструктаж EE'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='0', max_length=100, verbose_name='Name'),
        ),
    ]
